local listExecutorMap = {
	javascript = { comp = "node $realPath" },
	java = { comp = "cd $dir && javac $fileName && java $fileNameWithoutExt" },
	c = { comp = "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt" },
	zig = { comp = "zig run $realPath" },
	cpp = {
		comp = "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
		dbgComp = "cd $dir && g++ -g $fileName -o $fileNameWithoutExt",
	},
	php = { comp = "php $realPath" },
	python = { comp = "python -u $realPath" },
	perl = { comp = "perl $realPath" },
	perl6 = { comp = "perl6 $realPath" },
	ruby = { comp = "ruby $realPath" },
	go = { comp = "go run $realPath" },
	lua = { comp = "lua $realPath" },
	groovy = { comp = "groovy $realPath" },
	powershell = { comp = "powershell -ExecutionPolicy ByPass -File $realPath" },
	bat = { comp = "cmd /c $realPath" },
	shellscript = { comp = "bash $realPath" },
	fsharp = { comp = "fsi $realPath" },
	csharp = { comp = "scriptcs $realPath" },
	vbscript = { comp = "cscript //Nologo $realPath" },
	typescript = { comp = "ts-node $realPath" },
	coffeescript = { comp = "coffee $realPath" },
	scala = { comp = "scala $realPath" },
	swift = { comp = "swift $realPath" },
	julia = { comp = "julia $realPath" },
	crystal = { comp = "crystal $realPath" },
	ocaml = { comp = "ocaml $realPath" },
	r = { comp = "Rscript $realPath" },
	applescript = { comp = "osascript $realPath" },
	clojure = { comp = "lein exec $realPath" },
	haxe = { comp = "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt" },
	rust = { comp = "cd $dir && rustc $fileName && $dir$fileNameWithoutExt" },
	racket = { comp = "racket $realPath" },
	scheme = { comp = "csi -script $realPath" },
	ahk = { comp = "autohotkey $realPath" },
	autoit = { comp = "autoit3 $realPath" },
	dart = { comp = "dart $realPath" },
	pascal = { comp = "cd $dir && fpc $fileName && $dir$fileNameWithoutExt" },
	d = { comp = "cd $dir && dmd $fileName && $dir$fileNameWithoutExt" },
	haskell = { comp = "runghc $realPath" },
	nim = { comp = "nim compile --verbosity:0 --hints:off --run $realPath" },
	lisp = { comp = "sbcl --script $realPath" },
	kit = { comp = "kitc --run $realPath" },
	v = { comp = "v run $realPath" },
	sass = { comp = "sass --style expanded $realPath" },
	scss = { comp = "scss --style expanded $realPath" },
	less = { comp = "cd $dir && lessc $fileName $fileNameWithoutExt.css" },
	FortranFreeForm = { comp = "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt" },
	fortran_modern = { comp = "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt" },
	fortran_fixed_form = { comp = "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt" },
	fortran = { comp = "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt" },
	sml = { comp = "cd $dir && sml $fileName" },
}
return listExecutorMap
